### ISSUE TITLE
Not Working properly on Arch Linux

### ISSUE THREAD

**Issue by Stephan-MC** [genesisweb/valet-linux-plus#128]
I have Arch Linux with php 8.3 installed

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/c98817e6-3143-402b-aa31-38cacc26da62)

I installed valet properly without any errors. started the server without any errors....
i added my ```sites``` folder to be /srv/www as shown below

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/42105f15-1276-4c35-b300-c91d6a12a03d)

I changed my domain to 'localhost' (i prefer using .localhost over default '.test')

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/d4627309-a5a9-426e-9194-67e3388e9462)

when ever i run project.localhost (the directory /srv/www/proect exists and contains a laravel 11 project) in my browser, i get this page

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/ea7f8862-a791-46bf-923a-8212716f3065)

I checked the nginx error logs and got the following
![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/9f36312e-f1ba-45e3-8b44-14b76d78eed7)

**Comment by Stephan-MC** [comment]
After debugging for long period of time, i finally found the solution to my problem

it was related the to valet83.sock file. Ihad to regenerate a new one using

```fish
valet use
```

**Comment by uttamrabadiya** [comment]
@Stephan-MC I believe your issue is resolved by now, but you can always check Nginx log files to know more about this error.

Thank you!

**Comment by Stephan-MC** [comment]
Sorry i still got back to that error after running ``` valet install --mariadb```

and now, the previous solution i used doesn't work anymore but i still get the same errors

**Comment by uttamrabadiya** [comment]
@Stephan-MC Could you please share output of `nginx-error.log`, this file must be located on `~/.valet/Log` directory, also if you could attach output of nginx service status, you can check it by `sudo systemctl status nginx`

**Comment by Stephan-MC** [comment]
![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/98bdb62b-bd5d-4f96-a738-2ffddb1f2cbc)
this is the content of my ~/.valet/Log/nginx.error.log

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/c8898b2a-504e-4295-85bc-2b9f2b366600)
here is the content of the nginx service status... 

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/019e34b6-6cc2-4093-ad0e-6f8dc08c0462)
i later fixed the errors from nginx (modifying ~/.valet/Nginx/mails.localhost) but couldn't still open any php site

**Comment by uttamrabadiya** [comment]
@Stephan-MC If I read it right, then your log says that php-fpm service is not available, could you please check if valet83.sock file exists in `~/.valet` directory? If not then can you please run `sudo systemctl restart php8.3-fpm` command, if it still doesn't work then can you please share output of `sudo systemctl status php8.3-fpm` command

**Comment by Stephan-MC** [comment]
my php83-fpm is working correctly. this is screenshot of ``` sudo systemctl status php83-fpm ```

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/c231140f-b06e-41a3-8677-dd077c47ddad)

**Comment by uttamrabadiya** [comment]
Okay, can you please check if valet83.sock file exists in ~/.valet directory?

**Comment by Stephan-MC** [comment]
> Okay, can you please check if valet83.sock file exists in ~/.valet directory?

Yeah it's present
![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/14bb669c-acbc-43e7-887f-3b7c0e8a0289)

**Comment by uttamrabadiya** [comment]
@Stephan-MC  It's seems I am blind, I just re-checked your first screenshot and I notice that it you do not have `posix` extension installed in your system, can you please try installing it via `sudo apt install php8.3-posix php8.3-common --reinstall`, also could you please help me to understand what is your OS and version? I'd like to try on a fresh install

![image](https://github.com/genesisweb/valet-linux-plus/assets/48178542/d77b3d1a-0b5c-4604-a801-5ee4d96b3762)

**Comment by uttamrabadiya** [comment]
`sudo apt install php8.3-posix php8.3-common --reinstall` will not help you, as you are on Arch Linux, but you may can find equivalent command.

**Comment by Stephan-MC** [comment]
i have it installed.

![image](https://github.com/genesisweb/valet-linux-plus/assets/77833621/47c95059-948d-44be-aeb3-351707768988)

or i may interprete things wrongly

**Comment by Stephan-MC** [comment]
it was already installed before i got the errors i mentioned above

**Comment by uttamrabadiya** [comment]
Not sure if this will help but can you check if `posix_getpwuid` function is disabled in your system? Maybe you can do it by following: `php -r 'echo ini_get("disable_functions");'`

**Comment by Stephan-MC** [comment]
shows nothing...

**Comment by uttamrabadiya** [comment]
@Stephan-MC It seems some edge case, but maybe we can check it on screen, please email me on mail@uttam.dev, we may can have a small call to solve this issue.

**Comment by Stephan-MC** [comment]
> @Stephan-MC It seems some edge case, but maybe we can check it on screen, please email me on [mail@uttam.dev](mailto:mail@uttam.dev), we may can have a small call to solve this issue.

Check your mail. i Just emailed you...
